### ISSUE TITLE
Compiling or Executable to See the current state.

### ISSUE THREAD

**Issue by Werner1201** [Kmsxkuse/OV2#2]
Would I need unity to compile and see how the things are going ? or is there a compile executable and I just am dumb enough to not see it ?

**Comment by Kmsxkuse** [comment]
Oh, you'll need Unity to be able to "play" what I've made.

Once you've downloaded Unity 2019.1.8 (the current stable build), open the project and press play.

It's mainly just a loading screen as nothing else has been coded yet.
